#Mongo
quarkus.mongodb.connection-string=${DB_URL:mongodb://localhost:27017}
quarkus.mongodb.credentials.username=${DB_USER}
quarkus.mongodb.credentials.password=${DB_PASSWORD}
quarkus.mongodb.database=${DB_NAME}
quarkus.mongodb.credentials.auth-source=admin

#Logs
quarkus.log.category."org.mongodb.driver".level=WARN

#Internal services
biological-objects-api/mp-rest/url=http://search-biological-objects:8080